#!/usr/bin/env python3
"""
wiki_context.py — render the part of CLAUDE.md that should never be typed by hand.

## Why this exists

`CLAUDE.md` is per-repo on purpose: each wiki's rules differ. But three things inside it are either
**identical everywhere** or **derivable from this repo's own config**, and hand-copying them is why
they went wrong:

  * **The retrieval order.** On 2026-08-23 the source wiki learned to search before it reads, and
    `search.py` was synced to all ten wikis. Nobody updated the other nine CLAUDE.md files. On
    2026-09-04 an audit found **every wiki but the source still carried the pre-tiering instruction**
    -- *"read index.md FIRST, then drill in"* -- so nine wikis had the tool and no instruction to use
    it. Michelle noticed it as "my wiki is slow"; the corpus was fine, the reading discipline was
    six weeks out of date.

  * **Where this wiki sits.** `design/federation.json` knows the commons this wiki contributes to
    and receives from. CLAUDE.md, the file the model is told to read first, mostly did not mention
    it -- so "am I even connected to the commons?" was a fair question with no answer in the
    document meant to answer it.

  * **What this corpus is shaped like.** Whether sources are small and many or few and enormous
    changes how they should be read, and only the repo knows.

So: one marked block, generated from this repo, checked in CI. Everything outside the markers stays
hand-written and per-repo.

## What `--check` gates, and what it deliberately does not

Strictly: the federation wiring and the retrieval discipline. Those are the things that were
silently wrong for six weeks, and a stale one actively misleads.

Loosely: the corpus figures, which are rounded to a magnitude by `band()` so they change a
few times a year instead of on every ingest. Gating a byte-exact page count meant every PR
that added a page failed a check nobody had touched — see `band()` for why that is a defect
in the gate rather than a cost of having one.

Usage:
  python3 tools/wiki_context.py            # rewrite the block in CLAUDE.md
  python3 tools/wiki_context.py --check    # exit 1 if the block is missing or stale
  python3 tools/wiki_context.py --print    # render to stdout, change nothing
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
START = "<!-- wiki-context:start — generated by tools/wiki_context.py; do not edit by hand -->"
END = "<!-- wiki-context:end -->"
BIG_SOURCE_BYTES = 40_000          # ~10k tokens: past this, read a source in sections


def band(n: int) -> "tuple[int, bool]":
    """A count, rounded to a magnitude. Returns (value, was_rounded).

    The reason this exists is a defect, not tidiness. The block embeds counts and CI checks
    the block byte-for-byte, so **every pull request that added or removed a page failed a
    check nobody had touched** — 795 pages became 796 and `wiki_context.py --check` went red.
    Twice in one hour on 2026-09-07, on two different people's PRs. The standing fix was
    "run the tool again", which is how a gate stops being trusted and starts being routed
    around.

    But the numbers are not decoration: they exist so a model knows whether it is looking at
    a corpus of forty pages or eight hundred, and whether a source is small enough to read
    whole. Nothing anywhere depends on the exact value — 795 and 801 mean the same thing to
    every reader, human or not, while 795 and 1,500 do not.

    So the number is stored at the precision it is actually used at. The block then changes
    when the magnitude changes, a few times a year, and a regeneration means something.
    Small corpora stay exact: at eighteen pages, every page is a visible share of the whole.
    """
    if n < 25:
        return n, False
    step = 10 if n < 100 else 25 if n < 500 else 50
    # Half-UP, not round(): Python rounds halves to even, so 25 would band to 20 and read as
    # an understatement of a corpus a fifth larger than it says.
    return int(n / step + 0.5) * step, True


def count(n: int, unit: str) -> str:
    """`18 pages`, or `about 800 pages` once the figure is a magnitude rather than a count."""
    v, rounded = band(n)
    plural = unit if v == 1 else unit + "s"
    return f"about {v:,} {plural}" if rounded else f"{v:,} {plural}"


def _federation() -> dict:
    p = ROOT / "design" / "federation.json"
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def _corpus() -> tuple[int, int, int, int]:
    """(pages, source files, big source files, largest source bytes)"""
    wiki = ROOT / "wiki"
    pages = sum(1 for p in wiki.rglob("*.md")
                if p.relative_to(wiki).parts[0] not in {"log", "index"}
                and p.name not in {"log.md", "index.md"}) if wiki.is_dir() else 0
    # Only files git TRACKS. .gitignore excludes most binary sources, so a CI runner sees a
    # different raw/ than a local checkout -- and a block generated from the local view could
    # never match in CI. This is the same trap that keeps check_sources.py out of CI; the fix
    # here is to describe the repository, which is what git tracks, not the working directory.
    import subprocess
    try:
        out = subprocess.run(["git", "ls-files", "-z", "raw"], cwd=ROOT,
                             capture_output=True, text=True).stdout
    except OSError:
        out = ""
    tracked = [ROOT / f for f in out.split("\0") if f]
    sizes = [p.stat().st_size for p in tracked if p.is_file()]
    big = [s for s in sizes if s > BIG_SOURCE_BYTES]
    return pages, len(sizes), len(big), max(sizes, default=0)


def render() -> str:
    fed = _federation()
    name = fed.get("name") or ROOT.name
    role = fed.get("role", "spoke")
    ups = list(fed.get("contributes_to") or [])
    pages, n_src, n_big, largest = _corpus()

    L = [START, ""]
    L.append("## Where this wiki sits, and how to read it")
    L.append("")
    L.append("*Generated from `design/federation.json` and this repo. Run "
             "`python3 tools/wiki_context.py` after changing either; CI checks it is current.*")
    L.append("")

    # ── the federation, in plain words ────────────────────────────────────────────────────────
    L.append(f"**This wiki is `{name}`, a {role}.**")
    L.append("")
    if ups:
        names = [f"`{u}`" for u in ups]
        pretty = names[0] if len(names) == 1 else " and ".join([", ".join(names[:-1]), names[-1]])
        theirs = "its" if len(names) == 1 else "their"
        each = "it" if len(names) == 1 else "each of them"
        L.append(f"- **It is connected to {pretty}.** Yes — the connection is real and it runs "
                 f"in both directions.")
        L.append(f"- **Up:** when the owner says *\"share this with the team\"*, the `contribute` "
                 f"skill stages a sanitised, provenance-stamped bundle and opens a pull request "
                 f"against {each}. It never pushes. A `private` page is refused outright.")
        L.append(f"- **Down:** every day, {theirs} shared cut is cloned from {pretty} into "
                 f"`.commons/<name>/` "
                 f"so this wiki can read what the group knows. If `.commons/` is empty, run "
                 f"`python3 tools/sync_commons.py` — the cache is gitignored, so a fresh checkout "
                 f"has none and the tools that depend on it will look broken until it is filled.")
        L.append(f"- **What comes down is not merged.** It is there to be measured against: "
                 f"`delta` reads it, `gravity` reads it, and `contribution_prompt.py` uses it to "
                 f"name pages worth sharing. Nothing from a commons is written into `wiki/` "
                 f"without a person deciding.")
    else:
        L.append("- **Nothing sits above this wiki.** It is a top commons: other wikis contribute "
                 "*to* it, and it contributes onward to nobody. The `contribute` skill has no "
                 "target here, and that is correct rather than broken.")
    L.append("")

    # ── retrieval, identical everywhere ───────────────────────────────────────────────────────
    L.append("### Retrieval order — search, then graph, then read")
    L.append("")
    L.append("1. `python3 tools/search.py \"<question>\" --top 12` — ranks title, tags and "
             "description above body text, so the top hits are the pages the question is *about*. "
             "About 1k tokens.")
    L.append("2. `export/wiki.json` for the second hop — `inbound_links` / `outbound_links` make a "
             "page's neighbourhood a lookup rather than another search. It is gitignored and built "
             "by CI, so **if it is missing locally, run `python3 tools/export.py` once**; it costs "
             "seconds and saves whole searches.")
    L.append("3. Read the shortlist in full.")
    L.append("")
    L.append("**Never load pages in order to decide which pages to load.** Context is for reasoning "
             "over candidates; traversal is for finding them. Reading the index, or a shelf, to *see "
             "what exists* is fine — reading pages to triage them is the thing this replaces. A "
             "query should touch well under 30k tokens of corpus.")
    L.append("")

    # ── this corpus's own shape ───────────────────────────────────────────────────────────────
    L.append("### What this corpus is shaped like")
    L.append("")
    L.append(f"- **{count(pages, 'page')}** in `wiki/`, and "
             f"**{count(n_src, 'source file')}** in `raw/`.")
    if n_big:
        # Banded like the rest, and for the same reason: the share and the largest source are
        # read as "roughly how bad is this", never as figures anyone reconciles.
        share = int((100 * n_big / n_src) / 5 + 0.5) * 5 if n_src else 0
        tokens = largest // 4000
        tokens = int(tokens / 25 + 0.5) * 25 if tokens >= 100 else int(tokens / 5 + 0.5) * 5
        big_v, big_rounded = band(n_big)
        big_txt = f"about {big_v:,}" if big_rounded else f"{big_v:,}"
        L.append(f"- **{big_txt} of those sources are over "
                 f"{BIG_SOURCE_BYTES // 1000}KB** (about {share}% of them), the largest around "
                 f"**{tokens}k tokens**. That is a lot for one read.")
        L.append("- So: **do not read a large source end-to-end just to answer a question.** Grep "
                 "it, read the sections that matter, and say which sections you read. An `ingest` "
                 "does need the whole source — take it in passes, and write the summary as you go "
                 "rather than holding the entire document in context first.")
    else:
        L.append("- No single source is large enough to need special handling; read them whole.")
    L.append("")
    L.append(END)
    return "\n".join(L)


def current(text: str) -> str | None:
    if START not in text or END not in text:
        return None
    return text[text.index(START):text.index(END) + len(END)]


def apply_to(path: pathlib.Path) -> str:
    text = path.read_text(encoding="utf-8")
    block = render()
    if current(text) is not None:
        new = text[:text.index(START)] + block + text[text.index(END) + len(END):]
        path.write_text(new, encoding="utf-8")
        return "updated"
    # No markers yet: place the block after the opening section, before the first "## " heading,
    # so it is read early without displacing the constitution's own opening.
    i = text.find("\n## ")
    if i == -1:
        path.write_text(text.rstrip() + "\n\n" + block + "\n", encoding="utf-8")
    else:
        path.write_text(text[:i + 1] + block + "\n" + text[i:], encoding="utf-8")
    return "inserted"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Generate the wiki-context block in CLAUDE.md.")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--print", dest="show", action="store_true")
    args = ap.parse_args(argv)

    if args.show:
        print(render())
        return 0

    path = ROOT / "CLAUDE.md"
    if not path.exists():
        print("no CLAUDE.md in this repo — nothing to do.")
        return 0

    text = path.read_text(encoding="utf-8")
    if args.check:
        cur = current(text)
        if cur is None:
            print("CLAUDE.md has no wiki-context block — run: python3 tools/wiki_context.py",
                  file=sys.stderr)
            return 1
        if cur.strip() != render().strip():
            print("CLAUDE.md's wiki-context block is STALE — run: python3 tools/wiki_context.py",
                  file=sys.stderr)
            return 1
        print("wiki-context OK — CLAUDE.md matches this repo's federation and corpus.")
        return 0

    what = apply_to(path)
    fed = _federation()
    ups = ", ".join(fed.get("contributes_to") or []) or "nothing above it"
    print(f"{what} the wiki-context block in CLAUDE.md — {fed.get('name', ROOT.name)} "
          f"({fed.get('role', '?')}) → {ups}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
