#!/usr/bin/env python3
"""
wiki_context.py — render the part of CLAUDE.md that should never be typed by hand.

## Why this exists

`CLAUDE.md` is per-repo on purpose: each wiki's rules differ. But three things inside it are either
**identical everywhere** or **derivable from this repo's own config**, and hand-copying them is why
they went wrong:

  * **The retrieval order.** On 2026-08-23 the source wiki learned to search before it reads, and
    `search.py` was synced to all ten wikis. Nobody updated the other nine CLAUDE.md files. On
    2026-09-04 an audit found **every wiki but the source still carried the pre-tiering instruction**
    -- *"read index.md FIRST, then drill in"* -- so nine wikis had the tool and no instruction to use
    it. Michelle noticed it as "my wiki is slow"; the corpus was fine, the reading discipline was
    six weeks out of date.

  * **Where this wiki sits.** `design/federation.json` knows the commons this wiki contributes to
    and receives from. CLAUDE.md, the file the model is told to read first, mostly did not mention
    it -- so "am I even connected to the commons?" was a fair question with no answer in the
    document meant to answer it.

  * **What this corpus is shaped like.** Whether sources are small and many or few and enormous
    changes how they should be read, and only the repo knows.

So: one marked block, generated from this repo, checked in CI. Everything outside the markers stays
hand-written and per-repo.

Usage:
  python3 tools/wiki_context.py            # rewrite the block in CLAUDE.md
  python3 tools/wiki_context.py --check    # exit 1 if the block is missing or stale
  python3 tools/wiki_context.py --print    # render to stdout, change nothing
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
START = "<!-- wiki-context:start — generated by tools/wiki_context.py; do not edit by hand -->"
END = "<!-- wiki-context:end -->"
BIG_SOURCE_BYTES = 40_000          # ~10k tokens: past this, read a source in sections


def _federation() -> dict:
    p = ROOT / "design" / "federation.json"
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def _corpus() -> tuple[int, int, int, int]:
    """(pages, source files, big source files, largest source bytes)"""
    wiki = ROOT / "wiki"
    pages = sum(1 for p in wiki.rglob("*.md")
                if p.relative_to(wiki).parts[0] not in {"log", "index"}
                and p.name not in {"log.md", "index.md"}) if wiki.is_dir() else 0
    raw = ROOT / "raw"
    sizes = [p.stat().st_size for p in raw.rglob("*") if p.is_file()] if raw.is_dir() else []
    big = [s for s in sizes if s > BIG_SOURCE_BYTES]
    return pages, len(sizes), len(big), max(sizes, default=0)


def render() -> str:
    fed = _federation()
    name = fed.get("name") or ROOT.name
    role = fed.get("role", "spoke")
    ups = list(fed.get("contributes_to") or [])
    pages, n_src, n_big, largest = _corpus()

    L = [START, ""]
    L.append("## Where this wiki sits, and how to read it")
    L.append("")
    L.append("*Generated from `design/federation.json` and this repo. Run "
             "`python3 tools/wiki_context.py` after changing either; CI checks it is current.*")
    L.append("")

    # ── the federation, in plain words ────────────────────────────────────────────────────────
    L.append(f"**This wiki is `{name}`, a {role}.**")
    L.append("")
    if ups:
        names = [f"`{u}`" for u in ups]
        pretty = names[0] if len(names) == 1 else " and ".join([", ".join(names[:-1]), names[-1]])
        theirs = "its" if len(names) == 1 else "their"
        each = "it" if len(names) == 1 else "each of them"
        L.append(f"- **It is connected to {pretty}.** Yes — the connection is real and it runs "
                 f"in both directions.")
        L.append(f"- **Up:** when the owner says *\"share this with the team\"*, the `contribute` "
                 f"skill stages a sanitised, provenance-stamped bundle and opens a pull request "
                 f"against {each}. It never pushes. A `private` page is refused outright.")
        L.append(f"- **Down:** every day, {theirs} shared cut is cloned from {pretty} into "
                 f"`.commons/<name>/` "
                 f"so this wiki can read what the group knows. If `.commons/` is empty, run "
                 f"`python3 tools/sync_commons.py` — the cache is gitignored, so a fresh checkout "
                 f"has none and the tools that depend on it will look broken until it is filled.")
        L.append(f"- **What comes down is not merged.** It is there to be measured against: "
                 f"`delta` reads it, `gravity` reads it, and `contribution_prompt.py` uses it to "
                 f"name pages worth sharing. Nothing from a commons is written into `wiki/` "
                 f"without a person deciding.")
    else:
        L.append("- **Nothing sits above this wiki.** It is a top commons: other wikis contribute "
                 "*to* it, and it contributes onward to nobody. The `contribute` skill has no "
                 "target here, and that is correct rather than broken.")
    L.append("")

    # ── retrieval, identical everywhere ───────────────────────────────────────────────────────
    L.append("### Retrieval order — search, then graph, then read")
    L.append("")
    L.append("1. `python3 tools/search.py \"<question>\" --top 12` — ranks title, tags and "
             "description above body text, so the top hits are the pages the question is *about*. "
             "About 1k tokens.")
    L.append("2. `export/wiki.json` for the second hop — `inbound_links` / `outbound_links` make a "
             "page's neighbourhood a lookup rather than another search. It is gitignored and built "
             "by CI, so **if it is missing locally, run `python3 tools/export.py` once**; it costs "
             "seconds and saves whole searches.")
    L.append("3. Read the shortlist in full.")
    L.append("")
    L.append("**Never load pages in order to decide which pages to load.** Context is for reasoning "
             "over candidates; traversal is for finding them. Reading the index, or a shelf, to *see "
             "what exists* is fine — reading pages to triage them is the thing this replaces. A "
             "query should touch well under 30k tokens of corpus.")
    L.append("")

    # ── this corpus's own shape ───────────────────────────────────────────────────────────────
    L.append("### What this corpus is shaped like")
    L.append("")
    L.append(f"- **{pages} page(s)** in `wiki/`, and **{n_src} source file(s)** in `raw/`.")
    if n_big:
        share = round(100 * n_big / n_src) if n_src else 0
        L.append(f"- **{n_big} of those sources are over {BIG_SOURCE_BYTES // 1000}KB** ({share}% of "
                 f"them), the largest around **{largest // 4000}k tokens**. That is a lot for one "
                 f"read.")
        L.append("- So: **do not read a large source end-to-end just to answer a question.** Grep "
                 "it, read the sections that matter, and say which sections you read. An `ingest` "
                 "does need the whole source — take it in passes, and write the summary as you go "
                 "rather than holding the entire document in context first.")
    else:
        L.append("- No single source is large enough to need special handling; read them whole.")
    L.append("")
    L.append(END)
    return "\n".join(L)


def current(text: str) -> str | None:
    if START not in text or END not in text:
        return None
    return text[text.index(START):text.index(END) + len(END)]


def apply_to(path: pathlib.Path) -> str:
    text = path.read_text(encoding="utf-8")
    block = render()
    if current(text) is not None:
        new = text[:text.index(START)] + block + text[text.index(END) + len(END):]
        path.write_text(new, encoding="utf-8")
        return "updated"
    # No markers yet: place the block after the opening section, before the first "## " heading,
    # so it is read early without displacing the constitution's own opening.
    i = text.find("\n## ")
    if i == -1:
        path.write_text(text.rstrip() + "\n\n" + block + "\n", encoding="utf-8")
    else:
        path.write_text(text[:i + 1] + block + "\n" + text[i:], encoding="utf-8")
    return "inserted"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Generate the wiki-context block in CLAUDE.md.")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--print", dest="show", action="store_true")
    args = ap.parse_args(argv)

    if args.show:
        print(render())
        return 0

    path = ROOT / "CLAUDE.md"
    if not path.exists():
        print("no CLAUDE.md in this repo — nothing to do.")
        return 0

    text = path.read_text(encoding="utf-8")
    if args.check:
        cur = current(text)
        if cur is None:
            print("CLAUDE.md has no wiki-context block — run: python3 tools/wiki_context.py",
                  file=sys.stderr)
            return 1
        if cur.strip() != render().strip():
            print("CLAUDE.md's wiki-context block is STALE — run: python3 tools/wiki_context.py",
                  file=sys.stderr)
            return 1
        print("wiki-context OK — CLAUDE.md matches this repo's federation and corpus.")
        return 0

    what = apply_to(path)
    fed = _federation()
    ups = ", ".join(fed.get("contributes_to") or []) or "nothing above it"
    print(f"{what} the wiki-context block in CLAUDE.md — {fed.get('name', ROOT.name)} "
          f"({fed.get('role', '?')}) → {ups}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
